# Generated by Django 3.2.6 on 2021-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
